context('Task 4', () => {
    it('Test ARIA accordion show/hide', () => {
        cy.visit('http://localhost:4200/aria/accordion')
        cy.get('*[role="heading"]').should('have.length', 3)
        cy.get('*[role="region"]').should('have.length', 3)
        cy.get('*[role="heading"] a').eq(0).focus()
        cy.focused().type(' ')
        cy.get('*[role="region"]').eq(0).should('be.hidden')
        cy.focused().type(' ')
        cy.get('*[role="region"]').eq(0).should('not.be.hidden')
    })
    it('Test ARIA accordion navigate', () => {
        cy.visit('http://localhost:4200/aria/accordion')
        cy.get('*[role="heading"] a').eq(0).focus()
        cy.focused().contains('Panel 1').type('{downarrow} ')
        cy.focused().contains('Panel 2').type('{uparrow} ')
        cy.focused().contains('Panel 1').type('{uparrow} ')
        cy.focused().contains('Panel 3').type('{downarrow} ')
    })
})
